import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, "..");
const promptSourcePath = path.join(
  projectRoot,
  "docs/source_material/ThousandYearOldVampire Prompts.md",
);
const seedOutputPath = path.join(projectRoot, "supabase/seed.sql");
const appendixMarker = "Appendix I Alternate Prompt";

function normalizeWhitespace(value) {
  return value.replace(/\s+/g, " ").trim();
}

function escapeSql(value) {
  return value.replaceAll("'", "''");
}

function parseBasePromptRows(sourceText) {
  const [beforeAppendix] = sourceText.split(appendixMarker);
  const promptSection = beforeAppendix
    .split("The Prompts")
    .slice(1)
    .join("The Prompts")
    .trim();

  const promptBlocks = promptSection
    .split(/\n\s*\n/)
    .map((block) => normalizeWhitespace(block))
    .filter(Boolean)
    .filter((block) => block !== "•");

  return promptBlocks.map((promptMarkdown, index) => ({
    encounterIndex: 1,
    promptMarkdown,
    promptNumber: index + 1,
    promptVersion: "base",
  }));
}

function cleanAlternatePromptLead(value) {
  let cleaned = value.trim();

  while (/^\d+\.\s+/.test(cleaned)) {
    cleaned = cleaned.replace(/^\d+\.\s+/, "");
  }

  return cleaned;
}

function parseAlternatePromptRows(sourceText) {
  const appendixParts = sourceText.split(appendixMarker);
  const appendixText = appendixParts[1];

  if (!appendixText) {
    return [];
  }

  const lines = appendixText
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => line !== "ß")
    .filter((line) => !line.startsWith("•"));

  const rows = [];
  let currentPromptNumber = null;
  let currentEncounterIndex = 0;

  for (const line of lines) {
    const promptMatch = line.match(/^(\d+)\.\s+(.*)$/);

    if (promptMatch) {
      currentPromptNumber = Number.parseInt(promptMatch[1], 10);
      currentEncounterIndex = 1;
      rows.push({
        encounterIndex: currentEncounterIndex,
        promptMarkdown: normalizeWhitespace(
          cleanAlternatePromptLead(promptMatch[2]),
        ),
        promptNumber: currentPromptNumber,
        promptVersion: "alternate_appendix_i",
      });
      continue;
    }

    if (currentPromptNumber === null) {
      continue;
    }

    currentEncounterIndex += 1;
    rows.push({
      encounterIndex: currentEncounterIndex,
      promptMarkdown: normalizeWhitespace(line),
      promptNumber: currentPromptNumber,
      promptVersion: "alternate_appendix_i",
    });
  }

  return rows;
}

function buildSeedSql(rows) {
  const values = rows
    .map(
      ({ encounterIndex, promptMarkdown, promptNumber, promptVersion }) =>
        `  (${promptNumber}, ${encounterIndex}, '${escapeSql(promptMarkdown)}', '${escapeSql(promptVersion)}')`,
    )
    .join(",\n");

  return `-- Generated by scripts/seed-prompts.mjs. Do not edit by hand.
insert into public.prompt_catalog (
  prompt_number,
  encounter_index,
  prompt_markdown,
  prompt_version
)
values
${values}
on conflict (prompt_number, encounter_index, prompt_version) do update
set
  prompt_markdown = excluded.prompt_markdown;
`;
}

function main() {
  const sourceText = readFileSync(promptSourcePath, "utf8");
  const rows = [
    ...parseBasePromptRows(sourceText),
    ...parseAlternatePromptRows(sourceText),
  ];

  if (rows.length === 0) {
    throw new Error("No prompt rows were parsed from the local prompt source.");
  }

  mkdirSync(path.dirname(seedOutputPath), { recursive: true });
  writeFileSync(seedOutputPath, `${buildSeedSql(rows)}\n`, "utf8");

  const firstBasePrompt = rows.find((row) => row.promptVersion === "base");

  console.log(
    `Wrote ${rows.length} prompt rows to ${path.relative(projectRoot, seedOutputPath)}.`,
  );

  if (firstBasePrompt) {
    console.log(
      `Base prompt 1: ${firstBasePrompt.promptMarkdown.slice(0, 120)}`,
    );
  }
}

main();
